module github.com/martianoff/gala_demo_pkg_import

go 1.21



// GALA stdlib dependencies below. DO NOT EDIT.
// Code generated by gala transpiler. DO NOT EDIT.
require (
	martianoff/gala/collection_immutable v0.0.0
	martianoff/gala/collection_mutable v0.0.0
	martianoff/gala/concurrent v0.0.0
	martianoff/gala/std v0.0.0
	martianoff/gala/go_interop v0.0.0
)

replace martianoff/gala/collection_immutable => ./_gala/collection_immutable
replace martianoff/gala/collection_mutable => ./_gala/collection_mutable
replace martianoff/gala/concurrent => ./_gala/concurrent
replace martianoff/gala/std => ./_gala/std
replace martianoff/gala/go_interop => ./_gala/go_interop
// End GALA stdlib dependencies.

// GALA package dependencies below. DO NOT EDIT.
// Code generated by gala mod tidy. DO NOT EDIT.
require github.com/martianoff/gala_demo_pkg v0.2.3

replace github.com/martianoff/gala_demo_pkg => ./_gala/deps/github.com_martianoff_gala_demo_pkg@v0.2.3
// End GALA package dependencies.

// GALA-managed Go dependencies below. DO NOT EDIT.
// Code generated by gala mod tidy. DO NOT EDIT.
require (
	github.com/google/uuid v1.6.0 // indirect
)
// End GALA-managed dependencies.
